"""add AccessTokenBlackList

Revision ID: 653acb8a1038
Revises: e46e48d2aed9
Create Date: 2025-10-27 16:15:08.822771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653acb8a1038'
down_revision: Union[str, Sequence[str], None] = 'e46e48d2aed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token_black_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_token_black_list_id'), 'access_token_black_list', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_token_black_list_id'), table_name='access_token_black_list')
    op.drop_table('access_token_black_list')
    # ### end Alembic commands ###
