"""token table refactor

Revision ID: 786c4483013b
Revises: 58a95bc8e95f
Create Date: 2025-10-27 21:08:41.144178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786c4483013b'
down_revision: Union[str, Sequence[str], None] = '58a95bc8e95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_token_black_list_id'), table_name='access_token_black_list')
    op.drop_table('access_token_black_list')
    op.drop_index(op.f('ix_refresh_token_list_id'), table_name='refresh_token_list')
    op.drop_column('refresh_token_list', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token_list', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_refresh_token_list_id'), 'refresh_token_list', ['id'], unique=False)
    op.create_table('access_token_black_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('access_token_black_list_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('access_token_black_list_pkey'))
    )
    op.create_index(op.f('ix_access_token_black_list_id'), 'access_token_black_list', ['id'], unique=False)
    # ### end Alembic commands ###
