"""token table refactor

Revision ID: d6b600c153a0
Revises: 786c4483013b
Create Date: 2025-10-27 21:14:01.664601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b600c153a0'
down_revision: Union[str, Sequence[str], None] = '786c4483013b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'refresh_token_list', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token_list', type_='unique')
    # ### end Alembic commands ###
